apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: labs-nicolas
resources:
- deployment-backend.yaml
- deployment-frontend.yaml
- ingress.yaml
- service.yaml
images:
- name: nicolas333/backend
  newName: nicolas333/backend
  newTag: 14-
